name: Unit Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Perform a Pester test from the ConvertTo-Ini.Test.ps1 file
        shell: pwsh
        run: |
          Invoke-Pester ./module/tests/ConvertTo-Ini.Test.ps1 -Passthru
